### ISSUE TITLE
Cannot include or use default ontologies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Shuaib123/linqtordf#57]
```
What steps will reproduce the problem?
1. Create a application using LinqToRdf.
2. Include the RDF, RDFS, OWL, or XSDT ontology in your AssemblyInfo.cs
using the LinqToRdf.Ontology attribute.
3. Add an entity class that uses one of these ontologies.
4. Run your application.

I get the following error:
System.ArgumentException : an ontology already exists by that name
at LinqToRdf.NamespaceManager.set_Item(String name, OntologyAttribute
value) in D:\Program Files
(x86)\LinqToRdf\src\src\linqtordf\NamespaceManager.cs:line 105
at LinqToRdf.Sparql.SparqlQuery`1.CreateProlog(StringBuilder sb) in
D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 287
at LinqToRdf.Sparql.SparqlQuery`1.CreateSelectQuery(StringBuilder sb) in
D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 231
at LinqToRdf.Sparql.SparqlQuery`1.RunQuery() in D:\Program Files
(x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 192
at
LinqToRdf.Sparql.SparqlQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnum
erator()
in D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 127
at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
at LinqToRdf.Sparql.SparqlQuery`1.Execute[S](Expression expression) in
D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 102
at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
at ...

However, when I remove the ontology tags from my application I get the
following error:

System.NullReferenceException : Object reference not set to an instance of
an object.
at LinqToRdf.Sparql.SparqlQuery`1.CreateWhereClause(StringBuilder sb) in
D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 401
at LinqToRdf.Sparql.SparqlQuery`1.CreateSelectQuery(StringBuilder sb) in
D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 234
at LinqToRdf.Sparql.SparqlQuery`1.RunQuery() in D:\Program Files
(x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 192
at
LinqToRdf.Sparql.SparqlQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnum
erator()
in D:\Program Files (x86)\LinqToRdf\src\src\linqtordf\SparqlQuery.cs:line 127
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at ...

Please solve one (preferably both) errors.
```

Original issue reported on code.google.com by `ari...@gmail.com` on 27 Jan 2010 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
Please if you solve it tell me.
I need to use LinqToRdf to read FOAF.
```

Original comment by `elias.m....@gmail.com` on 8 Mar 2010 at 3:47
